apiVersion: apps/v1
kind: Deployment
metadata:
  name: winequality-flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: anjibabupalla/mlops_aks:latest
        ports:
        - containerPort: 5000      