# This is a basic workflow to help you get started with Actions

name: CI
env:
 APP_NAME: 'mlops_aks_gitworklow'
 resourceGroup: 'mlops'
 kubernetesVersion: '1.19.11'
 REGISTRY_NAME: 'azuremlopslearnacr'
 NAMESPACE: 'winequality' 
 CLUSTER_NAME: 'mlopsaks'
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{env.REGISTRY_NAME}}.azurecr.io
        # Username used to log against the Docker registry
        username: ${{secrets.REGISTRY_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.REGISTRY_PASSWORD}}
    - run: |
            docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
            docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }} 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

        # Create namespace if doesn't exist
    - run: |
            kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

        # Create image pull secret for ACR
    - uses: azure/k8s-create-secret@v1
      with:
       container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
       container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
       container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}       
       namespace: ${{ env.NAMESPACE }}
       force: true
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kube/deployment-dev.yaml
          kue/deployment-service-dev.yaml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        #imagepullsecrets: |
         # ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}
